# Generated by Django 4.2.3 on 2023-07-17 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(5)])),
                ('descriptions', models.TextField(max_length=255)),
                ('price', models.IntegerField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('belong_to_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.city')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='airport_price', to='viewer.airport')),
                ('hotel_price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_price', to='viewer.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='belong_to_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.country'),
        ),
        migrations.AddField(
            model_name='airport',
            name='belong_to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.city'),
        ),
    ]
