# Generated by Django 4.2.3 on 2023-07-21 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_airport_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('nr_adults', models.IntegerField()),
                ('places_for_children', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='board_type',
            field=models.CharField(choices=[('BB', 'Bed and Breakfast'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Inclusive')], default='None', max_length=2),
        ),
        migrations.AlterField(
            model_name='airport',
            name='belong_to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='viewer.city'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='city',
            name='belong_to_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='viewer.country'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='belong_to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='viewer.city'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='trip',
            name='from_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_trips', to='viewer.airport'),
        ),
        migrations.AddField(
            model_name='trip',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_trips', to='viewer.city'),
        ),
        migrations.AddField(
            model_name='trip',
            name='to_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_trips', to='viewer.airport'),
        ),
        migrations.AddField(
            model_name='trip',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_trips', to='viewer.city'),
        ),
    ]
