# Generated by Django 4.2.3 on 2023-07-28 19:25

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_from', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('age_to', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='board_type',
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(default=datetime.date(2023, 7, 28)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='nr_adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='places_for_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_date',
            field=models.DateField(default=datetime.date(2023, 7, 28)),
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_departure', models.DateField()),
                ('return_date', models.DateField()),
                ('number_of_adults', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_children', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hotel_price', models.FloatField(default=0)),
                ('airport_price', models.FloatField(default=0)),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_airports', to='viewer.airport')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_cities', to='viewer.city')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.hotel')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_airports', to='viewer.airport')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_cities', to='viewer.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='viewer.discount'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='viewer.discount'),
        ),
    ]
