# Generated by Django 4.2.3 on 2023-07-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='board_type',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='trip',
            name='nr_adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='places_for_children',
            field=models.IntegerField(default=0),
        ),
    ]
