# Generated by Django 4.2.3 on 2023-07-22 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_remove_hotel_board_type_remove_trip_departure_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(default=datetime.date(2023, 7, 22)),
        ),
        migrations.AddField(
            model_name='trip',
            name='return_date',
            field=models.DateField(default=datetime.date(2023, 7, 22)),
        ),
    ]
