# Generated by Django 4.2.3 on 2023-07-23 08:16

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_alter_discount_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(default=datetime.date(2023, 7, 23)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_date',
            field=models.DateField(default=datetime.date(2023, 7, 23)),
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_departure', models.DateField()),
                ('return_date', models.DateField()),
                ('number_of_adults', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_children', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_airports', to='viewer.airport')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_airports', to='viewer.airport')),
            ],
        ),
    ]
