# Generated by Django 4.2.3 on 2023-07-26 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_alter_trip_departure_date_alter_trip_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.hotel'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(default=datetime.date(2023, 7, 26)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_date',
            field=models.DateField(default=datetime.date(2023, 7, 26)),
        ),
    ]
