# Generated by Django 4.2.3 on 2023-07-28 11:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_alter_trip_departure_date_alter_trip_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_cities', to='viewer.city'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_cities', to='viewer.city'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(default=datetime.date(2023, 7, 28)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_date',
            field=models.DateField(default=datetime.date(2023, 7, 28)),
        ),
    ]
