# Generated by Django 4.2.3 on 2023-07-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_reservations_from_airport_reservations_to_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='from_airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_airports', to='viewer.airport'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='to_airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_airports', to='viewer.airport'),
        ),
    ]
