# Generated by Django 4.2.3 on 2023-07-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_alter_reservations_from_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='airport_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reservations',
            name='hotel_price',
            field=models.FloatField(default=0),
        ),
    ]
